version: '3'

services:
  nginx:
      image: nginx:latest
      ports:
          - "8080:80"
      depends_on: 
        - php
      volumes:
          - ./data:/data
          - ./nginx/site.conf:/etc/nginx/conf.d/default.conf

  php:
      build: ./php
      depends_on: 
        - db
      volumes:
          - ./data:/data


  db:
    image: mysql
    volumes:
      - ./mysql_data:/var/lib/mysql
   #   - ./dump:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_SECRET}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      
volumes:
  db_data: {}

#http://localhost:8080/wp-admin/install.php?step=2
#http://localhost:8080/wp-admin/
